INSERT INTO AIRPORT VALUES ('IXA', 'Agartala', 'Agartala Airport');
INSERT INTO AIRPORT VALUES ('AGX', 'Agatti', 'Agatti Airport');
INSERT INTO AIRPORT VALUES ('AGR', 'Agra', 'Agra Airport');
INSERT INTO AIRPORT VALUES ('AKD', 'Akola', 'Akola Airport');
INSERT INTO AIRPORT VALUES ('IXD', 'Allahabad', 'Allahabad Airport');
INSERT INTO AIRPORT VALUES ('IXV', 'Along', 'Along Airport');
INSERT INTO AIRPORT VALUES ('IXU', 'Aurangabad', 'Aurangabad Airport');
INSERT INTO AIRPORT VALUES ('IXB', 'Siliguri', 'Bagdogra Airport');
INSERT INTO AIRPORT VALUES ('BEK', 'Bareilly', 'Bareilly Air Force Station');
INSERT INTO AIRPORT VALUES ('BPM', 'Hyderabad', 'Begumpet Airport');
INSERT INTO AIRPORT VALUES ('IXG', 'Belgaum', 'Belgaum Airport');
INSERT INTO AIRPORT VALUES ('BEP', 'Bellary', 'Bellary Airport');
INSERT INTO AIRPORT VALUES ('BUP', 'Bathinda', 'Bathinda Airport');
INSERT INTO AIRPORT VALUES ('BHU', 'Bhavnagar', 'Bhavnagar Airport');
INSERT INTO AIRPORT VALUES ('BHJ', 'Bhuj', 'Bhuj Airport');
INSERT INTO AIRPORT VALUES ('BBI', 'Bhubaneswar', 'Biju Patnaik Airport');
INSERT INTO AIRPORT VALUES ('PAB', 'Bilaspur', 'Bilaspur Airport');
INSERT INTO AIRPORT VALUES ('IXR', 'Ranchi', 'Birsa Munda Airport');
INSERT INTO AIRPORT VALUES ('CCJ', 'Calicut', 'Calicut International Airport');
INSERT INTO AIRPORT VALUES ('CBD', 'Car Nicobar', 'Car Nicobar Air Force Station');
INSERT INTO AIRPORT VALUES ('IXC', 'Chandigarh', 'Chandigarh Airport');
INSERT INTO AIRPORT VALUES ('LKO', 'Lucknow', 'Chaudhary Charan Singh International Airport');
INSERT INTO AIRPORT VALUES ('MAA', 'Chennai', 'Chennai International Airport');
INSERT INTO AIRPORT VALUES ('BOM', 'Mumbai', 'Mumbai International Airport');
INSERT INTO AIRPORT VALUES ('COK', 'Kochi', 'Cochin International Airport');
INSERT INTO AIRPORT VALUES ('CJB', 'Coimbatore', 'Coimbatore International Airport');
INSERT INTO AIRPORT VALUES ('GOI', 'Vasco da Gama', 'Dabolim Airport');
INSERT INTO AIRPORT VALUES ('NMB', 'Daman and Diu', 'Daman Airport');
INSERT INTO AIRPORT VALUES ('DED', 'Dehradun', 'Dehradun Airport');
INSERT INTO AIRPORT VALUES ('IDR', 'Indore', 'Devi Ahilyabai Holkar Airport');
INSERT INTO AIRPORT VALUES ('DBD', 'Dhanbad', 'Dhanbad Airport');
INSERT INTO AIRPORT VALUES ('DIB', 'Dibrugarh', 'Dibrugarh Airport');
INSERT INTO AIRPORT VALUES ('DMU', 'Dimapur', 'Dimapur Airport');
INSERT INTO AIRPORT VALUES('NAG', 'Nagpur', 'Dr. Babasaheb Ambedkar International Airport');
INSERT INTO AIRPORT VALUES ('GAY', 'Gaya', 'Gaya Airport');
INSERT INTO AIRPORT VALUES('GOP', 'Gorakhpur', 'Gorakhpur Airport');
INSERT INTO AIRPORT VALUES ('GWL', 'Gwalior', 'Gwalior Airport');
INSERT INTO AIRPORT VALUES ('HSS', 'Hisar', 'Hisar Airport');
INSERT INTO AIRPORT VALUES('HBX', 'Hubli', 'Hubli Airport');
INSERT INTO AIRPORT VALUES ('IMF', 'Imphal', 'Imphal Airport');
INSERT INTO AIRPORT VALUES ('DEL', 'New Delhi', 'Indira Gandhi International Airport');
INSERT INTO AIRPORT VALUES ('JLR', 'Jabalpur', 'Jabalpur Airport');
INSERT INTO AIRPORT VALUES ('JAI', 'Jaipur', 'Jaipur International Airport');
INSERT INTO AIRPORT VALUES ('JSA', 'Jaisalmer', 'Jaisalmer Airport');
INSERT INTO AIRPORT VALUES ('IXJ', 'Jammu', 'Jammu Airport');
INSERT INTO AIRPORT VALUES ('JGA', 'Jamnagar', 'Jamnagar Airport');
INSERT INTO AIRPORT VALUES ('JDH', 'Jodhpur', 'Jodhpur Airport');
INSERT INTO AIRPORT VALUES ('JRH', 'Jorhat' , 'Jorhat Airport');
INSERT INTO AIRPORT VALUES ('CDP', 'Kadapa', 'Kadapa Airport');
INSERT INTO AIRPORT VALUES ('IXH', 'Kailashahar', 'Kailashahar Airport');
INSERT INTO AIRPORT VALUES ('IXY', 'Kandla', 'Kandla Airport');
INSERT INTO AIRPORT VALUES ('DHM', 'Kangra', 'Kangra Airport');
INSERT INTO AIRPORT VALUES ('CNN', 'Kannur', 'Kannur International Airport');
INSERT INTO AIRPORT VALUES ('KNU', 'Kanpur', 'Kanpur Airport');
INSERT INTO AIRPORT VALUES ('RDP', 'Durgapur', 'Kazi Nazrul Islam Airport');
INSERT INTO AIRPORT VALUES ('BLR', 'Bangalore', 'Kempegowda International Airport');
INSERT INTO AIRPORT VALUES ('IXK', 'Keshod', 'Keshod Airport');
INSERT INTO AIRPORT VALUES ('HJR', 'Khajuraho', 'Khajuraho Airport');
INSERT INTO AIRPORT VALUES ('KQH', 'Ajmer', 'Kishangarh Airport');
INSERT INTO AIRPORT VALUES ('KLH', 'Kolhapur', 'Kolhapur Airport');
INSERT INTO AIRPORT VALUES('KTU', 'Kota', 'Kota Airport');
INSERT INTO AIRPORT VALUES ('KUU', 'Bhuntar', 'Kullu-Manali Airport');
INSERT INTO AIRPORT VALUES ('VNS', 'Varanasi', 'Lal Bahadur Shastri Airport');
INSERT INTO AIRPORT VALUES ('IXL', 'Leh', 'Leh Kushok Bakula Rimpochee Airport');
INSERT INTO AIRPORT VALUES ('AJL', 'Aizawl', 'Lengpui Airport');
INSERT INTO AIRPORT VALUES ('PAT', 'Patna', 'Lok Nayak Jayaprakash Airport');
INSERT INTO AIRPORT VALUES ('GAU', 'Guwahati', 'Lokpriya Gopinath Bordoloi International Airport');
INSERT INTO AIRPORT VALUES ('LUH', 'Ludhiana', 'Sahnewal Airport');
INSERT INTO AIRPORT VALUES ('IXM', 'Madurai', 'Madurai Airport');
INSERT INTO AIRPORT VALUES ('UDR', 'Udaipur', 'Maharana Pratap Airport');
INSERT INTO AIRPORT VALUES ('IXE', 'Mangalore', 'Mangalore International Airport');
INSERT INTO AIRPORT VALUES ('LTU', 'Latur', 'Murod Kond Airport');
INSERT INTO AIRPORT VALUES ('MZU', 'Muzaffarpur', 'Muzaffarpur Airport');
INSERT INTO AIRPORT VALUES ('BKB', 'Bikaner', 'Nal Airport');
INSERT INTO AIRPORT VALUES ('NDC', 'Nanded', 'Nanded Airport');
INSERT INTO AIRPORT VALUES ('ISK', 'Nasik', 'Nashik Airport');
INSERT INTO AIRPORT VALUES ('CCU', 'Kolkata', 'Netaji Subhash Chandra Bose International Airport');
INSERT INTO AIRPORT VALUES ('IXI', 'Lilabari', 'North Lakhimpur Airport');
INSERT INTO AIRPORT VALUES ('PGH', 'Pantnagar', 'Pantnagar Airport');
INSERT INTO AIRPORT VALUES ('IXP', 'Pathankot', 'Pathankot Airport');
INSERT INTO AIRPORT VALUES ('PNY', 'Pondicherry', 'Pondicherry Airport');
INSERT INTO AIRPORT VALUES('PBD', 'Porbandar', 'Porbandar Airport');
INSERT INTO AIRPORT VALUES ('PNQ', 'Pune', 'Pune Airport');
INSERT INTO AIRPORT VALUES ('BHO', 'Bhopal', 'Raja Bhoj International Airport');
INSERT INTO AIRPORT VALUES ('RJA', 'Rajahmundry', 'Rajahmundry Airport');
INSERT INTO AIRPORT VALUES ('HYD', 'Hyderabad', 'Rajiv Gandhi International Airport');
INSERT INTO AIRPORT VALUES ('RAJ', 'Rajkot', 'Rajkot Airport');
INSERT INTO AIRPORT VALUES ('RTC', 'Ratnagiri', 'Ratnagiri Airport');
INSERT INTO AIRPORT VALUES ('REW', 'Rewa', 'Rewa Airport, Chorhata, REWA');
INSERT INTO AIRPORT VALUES ('RRK', 'Rourkela', 'Rourkela Airport');
INSERT INTO AIRPORT VALUES ('SXV', 'Salem', 'Salem Airport');
INSERT INTO AIRPORT VALUES ('AMD', 'Ahmedabad', 'Sardar Vallabhbhai Patel International Airport');
INSERT INTO AIRPORT VALUES ('SXR', 'Srinagar', 'Sheikh ul Alam Airport');
INSERT INTO AIRPORT VALUES ('SHL', 'Shillong', 'Shillong Airport');
INSERT INTO AIRPORT VALUES ('SAG', 'Shirdi', 'Shirdi Airport');
INSERT INTO AIRPORT VALUES('IXS', 'Silchar', 'Silchar Airport');
INSERT INTO AIRPORT VALUES ('SSE', 'Solapur', 'Solapur Airport');
INSERT INTO AIRPORT VALUES ('IXW', 'Jamshedpur', 'Sonari Airport');
INSERT INTO AIRPORT VALUES ('ATQ', 'Amritsar', 'Sri Guru Ram Dass Jee International Airport');
INSERT INTO AIRPORT VALUES ('PUT', 'Puttaparthi', 'Sri Sathya Sai Airport');
INSERT INTO AIRPORT VALUES  ('STV', 'Surat', 'Surat Airport');
INSERT INTO AIRPORT VALUES ('TEZ', 'Tezpur', 'Tezpur Airport');
INSERT INTO AIRPORT VALUES ('TRZ', 'Tiruchirappally', 'Tiruchirapally Civil Airport Airport');
INSERT INTO AIRPORT VALUES ('TRV', 'Thiruvananthapuram', 'Trivandrum International Airport');
INSERT INTO AIRPORT VALUES ('BDQ', 'Vadodara', 'Vadodara Airport' );
INSERT INTO AIRPORT VALUES ('VGA', 'Vijaywada', 'Vijayawada Airport');
INSERT INTO AIRPORT VALUES ('IXZ', 'Port Blair', 'Vir Savarkar International Airport');